### ISSUE TITLE
Design contribution

### ISSUE THREAD

**Issue by masudr4n4** [Mordag/repolizer#1]
Hallo 
I am Masud Rana .want to make a logo for this projects if you have any requirments then let me know.its free for any open source projects.
Thank you

**Comment by AlexanderEggers** [comment]
Hi Masud, 
Sure that would be awesome. I don't have any requirements to be honest. Do you have a rough idea how it will look like?

**Comment by masudr4n4** [comment]
which type logo you need please tel me. you have any idea?

**Comment by AlexanderEggers** [comment]
I have no idea to be honest. Most of the libraries I know of are not using any logos.

**Comment by masudr4n4** [comment]
my bad.sorry for disturb actually i can not found any idea about this projects to make  a logo.
Don't mind.
